FROM nginx:stable-alpine@sha256:0985e772fb9f729e6fa0980da05fca5d9c468e870eed43071545afa9d2e27d94

ENV NGINX_ENVSUBST_FILTER=FACTGRID_

COPY deploy/nginx/factgrid.conf.template /etc/nginx/templates/default.conf.template
COPY deploy/nginx/factgrid-proxy-headers.conf /etc/nginx/factgrid-proxy-headers.conf

EXPOSE 443
